import { getFormattedDate, getFormattedDateOnly, CustomgetFormattedDate } from './../../../.././utils.js';
import { faker } from '@faker-js/faker';
import { checkRow } from './../../../.././helper.ts';
import { test, expect } from '@playwright/test';

test.use({ storageState: './superadmin-auth.json' });

test('PLANNINGClasses_bot1', async ({ page }) => {
  test.setTimeout(50000);
  await page.goto('https://testing:NoMoreBugPlease01%21@preprod.g8ts.online/admin/');
  await page.hover('text=PLANNING'); await page.waitForTimeout(300); await page.getByRole('link', { name: 'Classes' }).click();
  await page.locator('.col-span-3 > .button').click();
  await page.getByRole('textbox', { name: 'Select Class' }).click();
  await page.getByRole('option', { name: 'Open Gym', exact: true }).click();
  await page.getByRole('textbox', { name: 'Select Location' }).click();
  await page.getByRole('option',  { name: 'West Bay - Gate Mall' }).click();
  await page.getByRole('textbox', { name: 'Select Trainer' }).click();
  await page.getByRole('option',  { name: 'Omar g8ts' }).click();
  await page.getByRole('textbox', { name: 'Select Room' }).click();
  await page.getByRole('option',  { name: 'Open Gym' }).click();
  await page.getByRole('textbox', { name: 'Start' }).click();
  await page.getByRole('textbox', { name: 'Start' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Start' }).fill(CustomgetFormattedDate());
  await page.getByRole('textbox', { name: 'Duration' }).click();
  await page.getByRole('textbox', { name: 'Duration' }).fill('10');
  await page.getByRole('spinbutton', { name: 'Capacity' }).click();
  await page.getByRole('spinbutton', { name: 'Capacity' }).fill('10');
  await page.getByRole('textbox', { name: 'Category', exact: true }).click();
  await page.getByRole('textbox', { name: 'Category', exact: true }).fill('testing');
  await page.getByRole('textbox', { name: 'Subcategory' }).click();
  await page.getByRole('textbox', { name: 'Subcategory' }).fill('testing');
  await page.getByRole('checkbox', { name: 'Visible' }).uncheck();
  await page.getByRole('checkbox', { name: 'Live' }).check();
  await page.getByRole('checkbox', { name: 'Visible' }).check();
  await page.getByRole('checkbox', { name: 'Live' }).uncheck();
  await page.getByRole('textbox', { name: 'Recorded video URL' }).click();
  await page.getByRole('textbox', { name: 'Recorded video URL' }).fill('testing');
 await page.getByRole('button', { name: 'Save' }).waitFor({ state: 'visible' });
  await page.getByRole('button', { name: 'Save' }).click({force: true});
  await page.waitForTimeout(2000); await page.locator('.toggle_details').first().click();
  await page.getByRole('link', { name: 'Book', exact: true }).click();
  await page.getByRole('combobox', { name: 'Search user by oxpin/' }).click();
  await page.getByRole('combobox', { name: 'Search user by oxpin/' }).fill('58694');
  await page.getByText('Mohammed Naseef MM Pin: 58694').click();
  await page.getByRole('textbox', { name: 'Select a status' }).click();
  await page.getByRole('option', { name: 'COMPLETED' }).click();
  await page.getByRole('textbox', { name: 'Select an option' }).click();
  await page.getByRole('option', { name: 'Cash' }).click();
  await page.getByRole('textbox', { name: 'Pincode' }).click();
  await page.getByRole('textbox', { name: 'Pincode' }).type('77', { delay: 100 });
  await page.getByRole('button', { name: 'Save' }).waitFor({ state: 'visible' });
  await page.getByRole('button', { name: 'Save' }).click();
  await page.waitForTimeout(2000); await page.locator('.toggle_details').first().click();
  await page.getByRole('link', { name: 'Book', exact: true }).click();
  await page.getByRole('combobox', { name: 'Search user by oxpin/' }).click();
  await page.getByRole('combobox', { name: 'Search user by oxpin/' }).fill('58694');
  await page.getByText('Mohammed Naseef MM Pin: 58694').click();
  await page.getByRole('textbox', { name: 'Select a status' }).click();
  await page.getByRole('option', { name: 'COMPLETED' }).click();
  await page.getByRole('textbox', { name: 'Select an option' }).click();
  await page.getByRole('option', { name: 'Cash' }).click();
  await page.getByRole('textbox', { name: 'Pincode' }).click();
  await page.getByRole('textbox', { name: 'Pincode' }).type('77', { delay: 100 });
  await page.getByRole('button', { name: 'Save' }).waitFor({ state: 'visible' });
  await page.getByRole('button', { name: 'Save' }).click({force: true});
  await page.waitForTimeout(2000); await page.locator('.toggle_details').first().click();
  await page.locator('.table-report__action > div > a:nth-child(2)').first().click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.locator('.whitespace-no-wrap > a:nth-child(2)').first().click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
});

