import { getFormattedDate,getFormattedDateOnly,CustomgetFormattedDate } from './../../../.././utils.js';
import { faker } from '@faker-js/faker';
import { test, expect } from '@playwright/test';
import { checkRow } from '../../../../helper.js';
test.use({ storageState: './superadmin-auth.json' });

test('REGISTRYPackages_bot1', async ({ page }) => {
  await page.goto('https://testing:NoMoreBugPlease01%21@preprod.g8ts.online/admin/');
  await page.hover('text=REGISTRY');     await page.waitForTimeout(300);     await page.getByRole('link', { name: 'Packages' }).click();
  await page.getByRole('link', { name: 'Add New' }).first().click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).dblclick();
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('testclasspack');
  await page.getByRole('textbox', { name: 'Price', exact: true }).click();
  await page.getByRole('textbox', { name: 'Price', exact: true }).fill('100');
  await page.getByRole('textbox', { name: 'Original Price' }).click();
  await page.getByRole('textbox', { name: 'Original Price' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Listing Order' }).click();
  await page.getByRole('spinbutton', { name: 'Listing Order' }).fill('1');
  await page.getByRole('textbox', { name: 'Select validity' }).click();
  await page.getByRole('option', { name: '3' }).click();
  await page.getByRole('spinbutton', { name: 'Number of visits' }).click();
  await page.getByRole('spinbutton', { name: 'Number of visits' }).fill('2');
  await page.getByRole('textbox', { name: 'Select Category' }).click();
  await page.getByRole('option', { name: 'opengym' }).click();
  await page.getByRole('textbox', { name: 'Select a company to attach' }).click();
  await page.getByRole('option', { name: 'opengym' }).click();
  await page.getByRole('textbox', { name: 'Event name' }).click();
  await page.getByRole('textbox', { name: 'Event name' }).fill('test');
  await page.getByRole('textbox', { name: 'Default Event Date' }).fill(getFormattedDateOnly());
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('testsgshshj');
  await page.locator('#class_pack_classes').selectOption({ index: faker.number.int({ min: 1, max: 2 }) });
  await page.getByRole('checkbox', { name: 'Active in POS' }).uncheck();
  await page.getByRole('checkbox', { name: 'Visible on the app' }).uncheck();
  await page.getByRole('checkbox', { name: 'Is Complimentary? (' }).check();
  await page.getByRole('checkbox', { name: 'Active in POS' }).check();
  await page.getByRole('checkbox', { name: 'Visible on the app' }).check();
  await page.getByRole('checkbox', { name: 'Is Complimentary? (' }).uncheck();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.locator('#class-pack-table').getByRole('button', { name: 'Last Page' }).click();
  await checkRow(page, "class-pack-table");
  await page.getByRole('textbox', { name: 'Name', exact: true }).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('updated');
  await page.getByRole('textbox', { name: 'Price', exact: true }).click();
  await page.getByRole('textbox', { name: 'Price', exact: true }).fill('10000');
  await page.getByRole('textbox', { name: 'Original Price' }).click();
  await page.getByRole('textbox', { name: 'Original Price' }).fill('1000');
  await page.getByRole('spinbutton', { name: 'Listing Order' }).click();
  await page.getByRole('spinbutton', { name: 'Listing Order' }).fill('2');
  await page.getByRole('textbox', { name: '3' }).click();
  await page.getByRole('option', { name: '4' }).click();
  await page.getByRole('spinbutton', { name: 'Number of visits' }).click();
  await page.getByRole('spinbutton', { name: 'Number of visits' }).fill('2');
  await page.locator('#select2-class_pack_category-container').click();
  await page.getByRole('option', { name: 'recovery' }).click();
  await page.getByRole('textbox', { name: 'opengym' }).click();
  await page.getByRole('option', { name: 'recovery' }).click();
  await page.getByRole('textbox', { name: 'Event name' }).click();
  await page.getByRole('textbox', { name: 'Event name' }).fill('upadteghej');
  await page.getByRole('textbox', { name: 'Default Event Date' }).fill(getFormattedDateOnly());
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('updated');
  await page.locator('#class_pack_classes').selectOption({ index: faker.number.int({ min: 1, max: 2 }) });
  await page.getByRole('checkbox', { name: 'Active in POS' }).uncheck();
  await page.getByRole('checkbox', { name: 'Visible on the app' }).uncheck();
  await page.getByRole('checkbox', { name: 'Is Complimentary? (' }).check();
  await page.getByRole('checkbox', { name: 'Active in POS' }).check();
  await page.getByRole('checkbox', { name: 'Visible on the app' }).check();
  await page.getByRole('checkbox', { name: 'Is Complimentary? (' }).uncheck();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Add New' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('servicepack');
  await page.getByRole('textbox', { name: 'Price' }).click();
  await page.getByRole('textbox', { name: 'Price' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Validity' }).click();
  await page.getByRole('spinbutton', { name: 'Validity' }).fill('5');
  await page.getByRole('spinbutton', { name: 'Number of visits' }).click();
  await page.getByRole('spinbutton', { name: 'Number of visits' }).fill('5');
  await page.getByRole('textbox', { name: 'Select Studio' }).click();
  await page.getByRole('option', { name: 'Equipt Fitness' }).click();
  await page.getByRole('spinbutton', { name: 'Listing Order' }).click();
  await page.getByRole('spinbutton', { name: 'Listing Order' }).fill('2');
  await page.getByRole('textbox', { name: 'Event name' }).click();
  await page.getByRole('textbox', { name: 'Event name' }).fill('nana');
  await page.getByRole('textbox', { name: 'Select a company to attach' }).click();
  await page.getByRole('option', { name: 'opengym' }).click();
  await page.locator('#service_pack_services').selectOption({ index: faker.number.int({ min: 1, max: 2 }) });
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('sdjhhjsdjd');
  await page.getByRole('checkbox', { name: 'Active in POS' }).uncheck();
  await page.getByRole('checkbox', { name: 'Visible on the app' }).uncheck();
  await page.getByRole('checkbox', { name: 'Is Complimentary? (' }).check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.locator('#service-pack-table > .tabulator-tableHolder > .tabulator-table > div > div').first().click();
  await page.getByRole('checkbox', { name: 'Visible on the app' }).check();
   await page.getByRole('textbox', { name: 'Name', exact: true }).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('ulcha');
  await page.getByRole('textbox', { name: 'Price' }).click();
  await page.getByRole('textbox', { name: 'Price' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Validity' }).click();
  await page.getByRole('spinbutton', { name: 'Validity' }).fill('5');
  await page.getByRole('spinbutton', { name: 'Number of visits' }).click();
  await page.getByRole('spinbutton', { name: 'Number of visits' }).fill('5');
  await page.locator('#service_pack_services').selectOption({ index: faker.number.int({ min: 1, max: 2 }) });
  await page.getByRole('spinbutton', { name: 'Listing Order' }).click();
  await page.getByRole('spinbutton', { name: 'Listing Order' }).fill('2');
  await page.getByRole('textbox', { name: 'Event name' }).click();
  await page.getByRole('textbox', { name: 'Event name' }).fill('nana');
  await page.locator('#service_pack_salesAttachment').selectOption({ index: faker.number.int({ min: 1, max: 2 }) });
  await page.locator('#service_pack_services').selectOption({ index: faker.number.int({ min: 1, max: 2 }) });
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('sdjhhjsdjd');
  await page.getByRole('checkbox', { name: 'Active in POS' }).uncheck();
  await page.getByRole('checkbox', { name: 'Visible on the app' }).uncheck();
  await page.getByRole('checkbox', { name: 'Is Complimentary? (' }).check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
});

