import { getFormattedDate,getFormattedDateOnly,CustomgetFormattedDate } from './../../../.././utils.js';
import { faker } from '@faker-js/faker';
import { checkRow } from './../../../.././helper.ts';
import { test, expect } from '@playwright/test';

test.use({
  storageState: './superadmin-auth.json'
});

test('test_planning-classes', async ({ page }) => {
  await page.goto('https://testing:NoMoreBugPlease01%21@preprod.g8ts.online/admin/');
  await page.hover('text=PLANNING'); await page.waitForTimeout(300); await page.hover('text=PLANNING'); await page.waitForTimeout(300); await page.hover('text=PLANNING'); await page.waitForTimeout(300); await page.hover('text=PLANNING'); await page.waitForTimeout(300); await page.hover('text=PLANNING'); await page.waitForTimeout(300); await page.getByRole('link', { name: 'Classes' }).click();
  await page.locator('.button.inline-block').first().click();
  await page.getByRole('textbox', { name: 'Select Class' }).click();
  await page.getByRole('option', { name: 'Recovery Oasis', exact: true }).click();
  await page.getByRole('textbox', { name: 'Select Location' }).click();
  await page.getByRole('option', { name: 'Rebound - Gate Mall' }).click();
  await page.getByRole('textbox', { name: 'Select Trainer' }).click();
  await page.getByRole('option', { name: 'Ezequiel Harvey Darien Kihn' }).click();
  await page.getByRole('textbox', { name: 'Select Room' }).click();
  await page.getByRole('option', { name: 'Recovery Room' }).click();
  await page.getByRole('textbox', { name: 'Start' }).click();
  await page.getByRole('textbox', { name: 'Start' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Start' }).fill(CustomgetFormattedDate());
  await page.getByRole('textbox', { name: 'Duration' }).click();
  await page.getByRole('textbox', { name: 'Duration' }).fill('10');
  await page.getByRole('spinbutton', { name: 'Capacity' }).click();
  await page.getByRole('spinbutton', { name: 'Capacity' }).fill('10');
  await page.getByRole('textbox', { name: 'Category', exact: true }).click();
  await page.getByRole('textbox', { name: 'Category', exact: true }).fill('dddddd');
  await page.getByRole('textbox', { name: 'Subcategory' }).click();
  await page.getByRole('textbox', { name: 'Subcategory' }).fill('ddddd');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('.toggle_details').first().click();
  await page.getByRole('link', { name: 'Book', exact: true }).click();
  await page.getByRole('combobox', { name: 'Search user by oxpin/' }).click();
  await page.getByRole('combobox', { name: 'Search user by oxpin/' }).fill('58694');
  await page.getByText('Mohammed Naseef MM Pin: 58694').click();
  await page.getByRole('textbox', { name: 'Select a status' }).click();
  await page.getByRole('option', { name: 'COMPLETED' }).click();
  await page.getByRole('textbox', { name: 'Select an option' }).click();
  await page.getByRole('option', { name: 'Cash' }).click();
  await page.getByRole('textbox', { name: 'Pincode' }).click();
  await page.getByRole('textbox', { name: 'Pincode' }).type('77', { delay: 100 });
  await page.getByRole('checkbox', { name: 'Force Create' }).check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('.toggle_details').first().click();
  await page.getByRole('link', { name: 'Book', exact: true }).click();
  await page.getByRole('combobox', { name: 'Search user by oxpin/' }).click();
  await page.getByRole('combobox', { name: 'Search user by oxpin/' }).fill('58694');
  await page.getByText('Mohammed Naseef MM Pin: 58694').click();
  await page.getByRole('textbox', { name: 'Select a status' }).click();
  await page.getByRole('option', { name: 'COMPLETED' }).click();
  await page.getByRole('textbox', { name: 'Select an option' }).click();
  await page.getByRole('option', { name: 'Cash' }).click();
  await page.getByRole('textbox', { name: 'Pincode' }).click();
  await page.getByRole('textbox', { name: 'Pincode' }).type('77', { delay: 100 });
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('.toggle_details').first().click();
  await page.locator('.flex.items-center.text-theme-6.delete-item.tooltip').first().click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.locator('.toggle_details').first().click();
  await page.locator('.flex.items-center.text-theme-6').first().click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
});